# Generated by Django 5.2.8 on 2025-11-07 22:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A human-readable name for this job (e.g., 'Bazos - BMW E30 Parts')", max_length=200)),
                ('target_url', models.URLField(max_length=1024)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle this job on or off')),
                ('scrape_interval', models.DurationField(default=datetime.timedelta(seconds=3600), help_text="How often to run the scrape (e.g., '1 hour', '30 minutes')")),
                ('css_selector_listing', models.CharField(help_text='CSS selector for the *container* of all listings', max_length=500)),
                ('css_selector_title', models.CharField(help_text='CSS selector for the item title (relative to the listing container)', max_length=500)),
                ('css_selector_price', models.CharField(help_text='CSS selector for the item price (relative to the listing container)', max_length=500)),
                ('css_selector_url', models.CharField(help_text="CSS selector for the item's unique URL (relative to the listing container)", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
